version: '3'
services:
    web:
        image: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./app/:/var/www/html"
        environment:
            - NGINX_HOST=${NGINX_HOST:-dev.local}
        command: "nginx -g 'daemon off;'"
        network_mode: "host"
        restart: always
        depends_on:
            - php
    php:
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/supervisor.conf:/etc/supervisor.conf"
            - "./app/:/var/www/html"
        build:
            context: .
            dockerfile: ./etc/docker/php/Dockerfile
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        environment:
            PHP_IDE_CONFIG: serverName=${NGINX_HOST:-dev.local}
            XDEBUG_CONFIG:  remote_host=${XDEBUG_LOCAL_IP:-192.168.0.12}
        network_mode: "host"
        restart: always
        depends_on:
            - mysqldb
    myadmin:
        build:
            context: .
            dockerfile: ./etc/docker/phpmyadmin/Dockerfile
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
            - PMA_PORT=${DB_PORT}
        network_mode: "bridge"
        ports:
            - "8081:80"
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: linuxserver/mariadb
        volumes:
            - "./data/mysql:/var/lib/mysql"
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
        restart: always
        network_mode: "host"
